import type { NextPage } from 'next';
import Head from 'next/head';
import Button from '@components/elem/button/Button';
import styled from 'styled-components';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Storybook Test Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<h1>Next + Storybook Test Page</h1>
				<section>
					<ButtonWrapper>
						<Button label="클릭" color="white" bgColor="primary" radius={10} />
					</ButtonWrapper>
				</section>
			</Main>
		</>
	);
};

export default Home;

const Main = styled.main`
	margin: auto;
	width: 600px;
	background: ${({ theme }) => theme.colors.bgColor2};
	border-top: 8px solid ${({ theme }) => theme.colors.primary};

	h1 {
		padding: 12px;
		font-size: ${({ theme }) => theme.textSize.m};
		font-weight: 700;
	}
`;

const ButtonWrapper = styled.div`
	margin: auto;
	width: 100%;
`;
